version: '3.8'

services:
  service1:
    build: .
    container_name: auth_service
    restart: always
    env_file:
      - ./service-1/.env
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8000:8000"  # Можно убрать наружу или поменять

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
